### ISSUE TITLE
Slower Night Day cycle 

### ISSUE THREAD

**Issue by AnticOwl** [slserpent/bl-sdk-mods#1]
Hello,

Not really an issue but more like a feature request.
Really happy that I have found this mod as I am currently playing and shooting BL2.
Would it be possible to have some keybinds (like ALT+F5/F6) for a slower inc/dec Time of Day?

**Comment by slserpent** [comment]
Have you not tried the recent update? It added an option to change the amount that increment shifted the time. You can go down to an equivalent of five mins.

**Comment by AnticOwl** [comment]
I just noticed it! It's nice. 
Probably me that like seeing these beautiful colours. Possible to go on the minute?

**Comment by AnticOwl** [comment]
It's OK like that.. 5 Minutes are enough for nice lights when taking pictures.
Nice work. Thanks a lot!
